### PR TITLE
Update 11-explore-the-azure-ai-extension.md

### PR DESCRIPTION
**Pull request by nachoalonsoportillo**
# Module: 00
## Lab/Demo: 00

Fixes # .

Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by nachoalonsoportillo** [comment]
Maybe we want to mention that the user can encounter this error when trying to deploy Language Service resource in a subscription on which Responsible AI terms have not been read and accepted.

`{"code": "InvalidTemplateDeployment", "message": "The template deployment 'deploy' is not valid according to the validation procedure. The tracking id is '41606ff3-8de4-4d57-804c-304e00843a35'. See inner errors for details."}

Inner Errors: 
{"code": "ResourceKindRequireAcceptTerms", "message": "This subscription cannot create TextAnalytics until you agree to Responsible AI terms for this resource. You can agree to Responsible AI terms by creating a resource through the Azure Portal then trying again. For more detail go to https://go.microsoft.com/fwlink/?linkid=2164190"}`

**Comment by nachoalonsoportillo** [comment]
Also, would be worth mentioning this one too:

`{"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/16af841d-db7d-4bd8-b606-c845c1a56152/resourceGroups/myresourcegrou_nacho/providers/Microsoft.Resources/deployments/deploy","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"ResourceDeploymentFailure","target":"/subscriptions/{subscriptionId}/resourceGroups/myresourcegrou_nacho/providers/Microsoft.DBforPostgreSQL/flexibleServers/psql-learn-eastus2-2baiar52p7ly4","message":"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'.","details":[{"code":"RegionIsOfferRestricted","message":"Subscriptions are restricted from provisioning in this region. Please choose a different region. For exceptions to this rule please open a support request with Issue type of 'Service and subscription limits'. See https://review.learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-request-quota-increase for more details."}]}]}}`

**Comment by nachoalonsoportillo** [comment]
This could also happen if user attempts to deploy more than once on the same subscription:

`{"code": "InvalidTemplateDeployment", "message": "The template deployment 'deploy' is not valid according to the validation procedure. The tracking id is '4e87a33d-a0ac-4aec-88d8-177b04c1d752'. See inner errors for details."}

Inner Errors: 
{"code": "FlagMustBeSetForRestore", "message": "An existing resource with ID '/subscriptions/{subscriptionId}/resourceGroups/myrg-nacho/providers/Microsoft.CognitiveServices/accounts/oai-learn-eastus-buhgtxv6ggkrw' has been soft-deleted. To restore the resource, you must specify 'restore' to be 'true' in the property. If you don't want to restore existing resource, please purge it first."}`

**Comment by kylebunting** [comment]
@nachoalonsoportillo, I have made multiple changes, so there are many conflicts between your PR and the current file. However, I went through your requested changes and incorporated them into the document. I also added info about common errors and solutions to the `Before you start` section of the document. Once you have a chance to review the updated document, you should be able to close this PR.

**Comment by nachoalonsoportillo** [comment]
@kylebunting Should I close this PR and review the current version already integrated in the main branch of MicrosoftLearning/mslearn-postgresql's repo?

Or is it the ADO repo the one I should be reviewing now?

**Comment by kylebunting** [comment]
@nachoalonsoportillo, I would close this PR and review the updated content in the main branch.

**Pull request closed without merging**
